apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "espresso-web.fullname" . }}
  labels:
    {{- include "espresso-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "espresso-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "espresso-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: regcred
      {{- end }}
      serviceAccountName: {{ include "espresso-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "espresso-web.fullname" . }}
          env:
          - name: ProductCatalogUrl
            valueFrom:
              configMapKeyRef:
                name: {{ include "espresso-web.fullname" . }}
                key: ProductCatalogUrl
          - name: ReviewsUrl
            valueFrom:
              configMapKeyRef:
                name: {{ include "espresso-web.fullname" . }}
                key: ReviewsUrl
          - name: RedisUrl
            valueFrom:
              configMapKeyRef:
                name: {{ include "espresso-web.fullname" . }}
                key: redisUrl
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
