apiVersion: v1
kind: Secret
metadata:
  name: {{ include "espresso-web.fullname" . }}
type: Opaque
data: 
  username:  {{ .Values.data.username }} # base64-encoded "admin"
  password: {{ .Values.data.password }} # base64-encoded "1f2d1e2e67df"
