apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "espresso-web.fullname" . }}
data:
  ProductCatalogUrl: "http://espresso-shop-product-catalog-svc:8091"
  ReviewsUrl: "http://espresso-shop-reviews-svc:8092"
  redisUrl: "http://redis-ha:6379"
  