apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.environment.review1.name }}
  labels:
    {{- include "espresso-review.labels_01" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "espresso-review.selectorLabels_01" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "espresso-review.selectorLabels_01" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: regcred
      {{- end }}
      # serviceAccountName: {{ .Values.environment.review1.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: postgres-secret
          # env:
          # - name: {{ include "espresso-review.fullname" . }}
          #   valueFrom:
          #     configMapKeyRef:
          #       name: {{ include "espresso-review.fullname" . }}
          #       key: SERVICE_VERSION
          env:
          - name: {{ .Values.environment.review1.key }}
            value: {{ .Values.environment.review1.value }}
          - name:  postgres-config
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name:  postgres-config
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          - name:  postgres-config
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_HOST

          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
